module.exports = {
	"wass":[
		"The sky! Hahaha",
		"Um... Prices?",
		"Not hell!",
		"Possibly, the temperature. But I'm no weather man.",
		"The atmosphere.",
		"Raisins! *throws raisins into the air*",
		"My hair. If I had hair.",
		"Slenderman, probably.",
		"Extinction rates. Of the human species, especially. Soon I'll be free...",
		"1. Toward the sky or a higher position.\n2. To the place where someone is.",
		"The ceiling.",
		"My love for you! :purple_heart:",
		"Not Rick Astley~"
	],
	"lovebombs": [
		"I love you very much, msg.author.username",
		"Please stay safe.",
		"I would miss you very much if you left. I think we all would.",
		"You mean a lot to me.",
		"If anyone tells you that you are not loved, do not listen. You are more loved than you could ever imagine.\nI am happy to be one person that says that they love you."
	],
	"numbers": [
		"zero",
		"one",
		"two",
		"three",
		"four",
		"five",
		"six",
		"seven",
		"eight",
		"nine",
		"ten",
		"eleven",
		"twelve",
		"thirteen",
		"fourteen",
		"fifteen",
		"sixteen",
		"seventeen",
		"eighteen",
		"ninteen",
		"twenty"
	],
	"pollnumbers": [
		"0️⃣",
		"1️⃣",
		"2️⃣",
		"3️⃣",
		"4️⃣",
		"5️⃣",
		"6️⃣",
		"7️⃣",
		"8️⃣",
		"9️⃣",
		"🔟"
	],
	"codestab": "abcdefghijklmnopqrstuvwxyz1234567890",
	"pressf": [
		"<:pressf:692902549183004673>",
		"<a:fspin:543851155562954753>",
		"<a:fspinfast:543851120511156224>"
	],
	"welc_strings": {
		"$MEMBER.MENTION":"${member.mention}",
		"$MEMBER.NAME":"${member.username + '#' + member.discriminator}",
		"$MEMBER.ID":"${member.id}",
		"$GUILD.NAME":"${guild.name}"
	},
	"emoji": {
		"#": "#️⃣",
		"0": "0️⃣",
		"1": "1️⃣",
		"2": "2️⃣",
		"3": "3️⃣",
		"4": "4️⃣",
		"5": "5️⃣",
		"6": "6️⃣",
		"7": "7️⃣",
		"8": "8️⃣",
		"9": "9️⃣",
		"a": "🇦",
		"b": "🇧",
		"c": "🇨",
		"d": "🇩",
		"e": "🇪",
		"f": "🇫",
		"g": "🇬",
		"h": "🇭",
		"i": "🇮",
		"j": "🇯",
		"k": "🇰",
		"l": "🇱",
		"m": "🇲",
		"n": "🇳",
		"o": "🇴",
		"p": "🇵",
		"q": "🇶",
		"r": "🇷",
		"s": "🇸",
		"t": "🇹",
		"u": "🇺",
		"v": "🇻",
		"w": "🇼",
		"x": "🇽",
		"y": "🇾",
		"z": "🇿",
		"!": "❗",
		"?": "❓"
	},
	"thinkemote": "<:thinksteve:646257084060663818>",
	"choices": [
		"How about $CHOICE?",
		"Hmm... I say $CHOICE.",
		"Why not $CHOICE?",
		"You know you want $CHOICE~",
		"I'm going for $CHOICE.",
		"Go with $CHOICE!"
	],
	"weekdays": [
		"sunday",
		"monday",
		"tuesday",
		"wednesday",
		"thursday",
		"friday",
		"saturday",
		"sun",
		"mon",
		"tues",
		"wed",
		"thurs",
		"fri",
		"sat"
	],
	"coolness": [
		"Super chilly! :cloud_snow:",
		"Absolutely frozen! :ice_cube:",
		"Freezing! :snowflake:",
		"Lukewarm! :tea:",
		"Burning up! :fire:"
	],
}
